# Generated by Django 3.2.9 on 2021-11-30 04:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('elimination_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='noticia/', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('elimination_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='servicio/', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
