# Generated by Django 3.2.9 on 2021-11-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='image',
            field=models.ImageField(upload_to='servicio/', verbose_name='Imágen'),
        ),
    ]
