# Generated by Django 3.2.9 on 2021-11-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_noticias_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Services',
        ),
    ]
