# Generated by Django 3.2.9 on 2021-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211130_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='experience',
            field=models.IntegerField(verbose_name='Años de Experiencia'),
        ),
    ]
