# Generated by Django 3.2.9 on 2021-11-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_business_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banners',
        ),
    ]
