# Generated by Django 3.2.9 on 2021-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_banner_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Información de la Empresa', 'verbose_name_plural': 'Información de la empresa'},
        ),
        migrations.AlterField(
            model_name='business',
            name='image_01',
            field=models.ImageField(null=True, upload_to='empresa/', verbose_name='Imágen 1'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_02',
            field=models.ImageField(null=True, upload_to='empresa/', verbose_name='Imágen 2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_03',
            field=models.ImageField(null=True, upload_to='empresa/', verbose_name='Imágen 3'),
        ),
    ]
