# Generated by Django 3.2.9 on 2021-12-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211202_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image_03',
        ),
    ]
