# Generated by Django 3.2.9 on 2021-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_business_image_03'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('elimination_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.CharField(max_length=120, verbose_name='Correo Electrónico')),
                ('cel', models.CharField(max_length=18, verbose_name='Número de Contacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
